#!name=小红书账号创建日期
#!desc=在小红书 App 用户主页显示根据 User ID 推算的账号创建日期
#!author=theog0g
#!homepage=https://github.com/theog0g/xiaohongshu-account-date

[rewrite_local]

^https:\/\/edith\.xiaohongshu\.com\/api\/sns\/v3\/user\/info url script-response-body https://raw.githubusercontent.com/theog0g/xiaohongshu-account-date/main/quantumultx/xiaohongshu-account-date.js

[mitm]

hostname = edith.xiaohongshu.com